name: UltimateCommands
version: 0.0.5
author: Arthurdw
main: net.xiler.mc.UltimateCommands.Main
description: The all in one command plugin aimed for controllability.

commands:
  uc:
    aliases:
      - ultimatecommands
      - ulticommands
      - ulticmd
      - ultic
      - ucmd
      - ucomm
      - ucommands
    description: Returns the help menu!
  fly:
    description: Enable/Disable flight!
  survival:
    aliases: [gms]
    description: Change your gamemode to survival!
  adventure:
    aliases: [gma]
    description: Change your gamemode to adventure!
  creative:
    aliases: [gmc]
    description: Change your gamemode to creative!
  spectator:
    aliases: [gmsp]
    description: Change your gamemode to spectator!
  broadcast:
    aliases:
      - bc
      - alert
      - announce
    description: Broadcast a message to your whole server!
